### ISSUE TITLE
HDTV is old now

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#22]
In the conclusions we say:

> About a thousand observations of each position across half of the Celestial Sphere will
> represent the greatest movie of all time: assuming HDTV resolution (2.1 Mpix/frame) with
> 30 frames per second, and 270 color images per position
> (e.g., the $ugr$ and $izy$ color-composites, c.f. Table~\ref{tab:baseline}), it would take
> about eleven uninterrupted months to view this color movie (equivalent
> to about 4,000 feature films).

but this is now showing its age because these days we watch movies in 4K UltraHD resolution (8.3 Mpix/frame). Also, to be pedantic, movies are usually 24 frames per second and not 30.

ie, the pixel count is 4 times too low but the frame rate is 1.25 times too high. I think this means our "feature films" number is 3.2 times too big.

**Comment by ivezic** [comment]
Yes, this is dated text and a leftover from the fundraising days... 
I propose that we remove that text (I'd do it but don't want
to collide with you - please let me know if that concern 
is now moot [also, we need to give a signal to Michael when
it's ok for him to resume editing]).

**Comment by timj** [comment]
I am not editing text at the moment. I'm working on author lists now. I have told @michaelstrauss he has permission to edit.

**Comment by timj** [comment]
Fixed in 6d8e005ed0441751322a8da92bbea3ab38f0af6a
