### ISSUE TITLE
Remove the postscript files?

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#24]
Do we really need all the postscript files clogging up the repository? Modern latex can convert PDF to EPS on the fly if you are wanting to generate postscript output. The postscript files take up space in the directory and aren't needed.

**Comment by ivezic** [comment]
Yes, postscript is leftover from dark ages. We could remove them,
though I note that we don't pay much for the used space :)

**Comment by timj** [comment]
I removed them in #25
