### ISSUE TITLE
How many galaxies?

### ISSUE THREAD

**Issue by drphilmarshall** [lsst-pst/overview_paper#28]
@ivezic In the Dark Energy sections of the overview paper we refer to a sample of several billion galaxies, but the abstract still says 20 billion. I think this larger number is what was used in the sizing model, but it is not what we would estimate for the actual number of useable galaxies for cosmology. Can we propagate the term "several billion" into the abstract of the overview paper please, to help support public talks etc?  I see that the key numbers confluence page also gives an estimate of 20 billion galaxies - I'll issue this suggestion over there as well.

**Comment by ivezic** [comment]
There are different sample definitions: all galaxies detected to the survey 
limit (r<27.5, i<26.8) vs. galaxies in the brighter "gold" sample (i<25.3) that 
will have SNR high enough for cosmological use. The former is estimated to 
about 15 billion, +-20-30%, which we rounded up to 20 billion (10-20 billion 
might be a more precise statement), using eq. 3.7 from the LSST Science 
Book. The latter is estimated to be ~4 billion. One can do additional cuts on 
the gold sample, e.g. to select galaxies sufficiently resolved for WL analysis, 
etc. The abstract refers to the full sample so 20 billion is correct (or 10-20 
billion if one is picky).

**Comment by timj** [comment]
@ivezic can you please close this issue if you don't feel there is anything further to discuss?

**Comment by ivezic** [comment]
I think we can close it (for the above reasons, we still use 20 billion galaxies
in the abstract.
