### ISSUE TITLE
ApJ#1: Starbucks

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#33]
The "Deep-Wide-Fast" survey is supplemented by a "Very Deep" survey and a "Fast time domain" survey [in the abstract]. This is too reminiscent of Starbucks' coffee sizes, where "grande" isn't big.

**Comment by ivezic** [comment]
It seems that the referee split "Very Deep and Fast time domain survey" into two surveys: "Very Deep"
and "Fast". While somewhat silly comment, we could replace "Very Deep and Fast time domain survey" 
by "Very Deep time domain survey" and "Very Fast time domain survey" to pacify him/her.

**Comment by ivezic** [comment]
> The "Deep-Wide-Fast" survey is supplemented by a "Very Deep" survey and a "Fast time domain" 
> survey [in the abstract]. This is too reminiscent of Starbucks' coffee sizes, where "grande" isn't big.

"Very" was meant to apply to both "Deep" and "Fast"; fixed.
