### ISSUE TITLE
ApJ #1: Filter change time

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#36]
State how long it takes to change filters. This is relevant for getting an SED of a rapidly changing transient.

**Comment by ivezic** [comment]
Steve, what's your official position here?

**Comment by cclaver** [comment]
Filter change time is specified as 120sec, where 30 seconds is allocated to rotate the camera into its "zero position" and 90 seconds allocated to the filter change itself.  The 30 second rotator allocation is based on the rotator being at or near one of its limits and a 90 degree rotation is required.  In practice this will not be the case and the rotation time will be less.

**Comment by ivezic** [comment]
We have added this information to section 2.6.2: "The five filters in the camera can be changed in 
90-120 seconds, depending on the initial camera rotator position."
