### ISSUE TITLE
ApJ #1: ZTF experience and alert types

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#37]
The Zwicky Transient Facility is up and running, and the author list of this paper includes many ZTF team members. Based on ZTF experience, you should have a fairly good updated estimate of what the LSST transient alert stream should look like. While you do mention several million alerts per night, you should mention how these will break down into supernovae, fast transients, stellar flares, and asteroids.

**Comment by ivezic** [comment]
Eric, can you please provide a few wise words here?

**Comment by ivezic** [comment]
Hm, Eric Bellm is not in the list of offered potential assignees... I will send him email.

**Comment by ivezic** [comment]
Our ZTF colleagues report that they don't have robust results yet and claim that a paper describing
LSST simulations by Ridgway et al. (2014) is still the best reference. We have added a reference to
that paper (not including it was an omission on our part).
