### ISSUE TITLE
ApJ #1: Standard sirens will not be found

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#38]
Standard sirens will not be "found" by LSST [p 36]. They have to found and measured using LIGO/VIRGO/KAGRA/IndIGO and then the EM counterparts need to be found, and LSST will be a great asset for this follow-up activity. So rewrite this to say LSST will followup GWB alerts and is likely to find 70 EM counterparts if the gravitational wave network is working well.

**Comment by ivezic** [comment]
Fed, Phil, I am not sure where the text about standard sirens came from. 
Can you please help by tracing its origin and responding to this comment?

**Comment by ivezic** [comment]
Weirdness again - it doesn't have Phil in the list of potential assignees...
Fed, can you please catch Phil?

**Comment by ivezic** [comment]
Excellent point! Implemented as suggested.
