### ISSUE TITLE
ApJ #1: Explain size distribution

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#40]
On page 28, H does NOT scale directly with the diameter of an object. That would say that an object with D=1400 m would have H=220 since an object with H=22 has D=140 m for albedo = 14%. H is a logarithmic quantity representing a flux which scales quadratically with diameter. Explain what size distribution is equivalent to your dN/dH~10^{H/3}.

**Comment by ivezic** [comment]
Well, the referee is correct that the following statement "For a given albedo, H scales directly with diameter of the asteroid." is plain wrong. Lynne, can you please address this comment?

**Comment by ivezic** [comment]
We agree that our phrasing of this well known relation was poor. We have modified
the text as suggested and clarified that adopted magnitude distribution corresponds 
to a size distribution $dN/dD \propto 1/D^\beta$, with $\beta = 5\alpha+1$.
