### ISSUE TITLE
ApJ #1: Color accuracy cf SDSS

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#41]
The claim in Figure 24 that LSST colors will be twice as accurate as SDSS colors for asteroids depends on being able to phase up very sparse light curves in the different filters, which will be a considerable task, while the SDSS filters were all obtained within about 2 minutes.

**Comment by ivezic** [comment]
The referee has a good point. I will add this caveat to the manuscript.

**Comment by ivezic** [comment]
Hm, it's not as bad as it sounds: even if we didn't phase them up, on average amplitudes are about 0.3 mag, so ~0.3/sqrt(100)=0.03 mag which is not bad at all. But we can also point out section 5.7.1 on "Sparse lightcurve inversion" from the LSST Science Book (https://www.lsst.org/scientists/scibook).
If you have references to PTF and Pan-STARRS examples, please send them to me.
I will take care of this issue.

**Comment by ivezic** [comment]
The accuracy of SDSS colors is about 0.03 mag (0.02 mag errors per band with uncorrelated errors), 
when the achieved SNR allows it. Assuming that the rms for asteroid light curves is ~0.2 mag (e.g. 
an amplitude of 0.3 mag and sinusoidal variation), and 100 observations per band, the expected 
color accuracy is 0.02 mag (0.2/sqrt(100) with correlated errors between bands). This color accuracy
is achieved without any light curve phasing (and the rizy bands have more than 100 observations).
In addition, a discussion about "Sparse lightcurve inversion" in section 5.7.1 from the LSST Science 
Book (https://www.lsst.org/scientists/scibook) shows that light curve inversion, while "a considerable 
task", will not be a hopeless task. Thus, we believe that our statement is correct.
