### ISSUE TITLE
ApJ #1: Asteroid photometry accuracy

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#42]
\S 2.1.2: It should be noted in the text that this requirement: 

> "The photometry should be better than 1-2% to measure asteroids' colors and thus determine their types. The different filters should be observed over a short time span to reduce apparent variations in color due to changes in observing geometry, but should be repeated over many lunations in order to determine phase curves and allow shape modeling."

is not met by the proposed main survey. The typical asteroid changes its flux by 1% in 100 seconds or so. The filter change cycle is hard to find - I suppose I could look at minion_1016 - but I believe it is on a much longer time scale than 100 seconds. Thus the caption of Figure 24 stating that LSST colors will be twice as good as SDSS colors is not supported. SDSS observed all 5 bands in O(10^2) seconds, while LSST may well take days.

**Comment by ivezic** [comment]
Similar to #41 - I will clarify.

**Comment by ivezic** [comment]
The time to change the filter in the camera is 90-120 seconds, and following your suggestion, 
this information was added to the manuscript. But given the discussion about asteroid color accuracy 
just  above, we believe that the required accuracy will be achieved even without back-to-back observations in different filters (though we anticipate that some tests based on back-to-back observations will be done to empirically confirm the claim of ~2% color accuracy).
