### ISSUE TITLE
ApJ #1: Weak lensing background comparison

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#45]
How does the effective number density of weak lensing background galaxies compare with Euclid and WFIRST? Euclid is observing a similarly large area with a better PSF, no seeing, no weather, no Moon, no daytime, and a darker sky.

**Comment by ivezic** [comment]
Fed, could you please work with Phil and the WL collaboration to address this comment?

**Comment by fedhere** [comment]
I punted this to @drphilmarshall (cause I do not have the competence to answer) - I will check w him on the status

**Comment by ivezic** [comment]
@drphilmarshall  any updates? It'd be great if we could resubmit in a couple of weeks...

**Comment by timj** [comment]
Fixed in #53
