### ISSUE TITLE
ApJ #1: Update figure 22 on weak lensing

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#46]
The weak lensing results will be competing with Euclid which has a similar start date. There are several surveys that have been "skimming the cream on weak lensing science", including CFHTLenS, PanSTARRS and DES. So far the cream has not produced spectacular results. Figure 22 seems frozen in the DETF days. Figure 22 should acknowledge the surveys in the can, and show an "All" that include Euclid WL and then "All minus LSST WL". So you should include a fair assessment of how much the LSST will advance the field over where it will be given current and under construction surveys.

**Comment by ivezic** [comment]
Fed, could you please work with Phil and the WL collaboration to address this comment?
It seems much more work than #45...

**Comment by fedhere** [comment]
@drphilmarshall can you address this comment? I think you are the best person for the job

**Comment by ivezic** [comment]
@drphilmarshall  any updates? It'd be great if we could resubmit in a couple of weeks...

**Comment by timj** [comment]
Fixed in #53
