### ISSUE TITLE
ApJ #1: Proper motion and parallax accuracy

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#47]
In discussing the proper motion and parallax accuracy, it should be pointed out that achieving the required 10 mas 1 sigma 1 axis single visit accuracy requires SNR of 30, so the magnitude limit is 2 mag brighter than the single visit SNR 5 limit. Still very good: r = 22.5. Later on p 29 there is a more conservative  calculation showing r = 21 for 0.2 mas/yr. So give a magnitude limit during the first proper motion accuracy discussion, and state that accuracy scales like 1/flux for fainter objects.

**Comment by ivezic** [comment]
I will address this one (with help from Dave Monet if need be).

**Comment by ivezic** [comment]
We have clarified that the first mention of "10 mas" corresponds to systematic astrometric errors 
(and not random errors which indeed scale as 1/flux, as discussed in Section 3.2.3)
