### ISSUE TITLE
ApJ #1: Cite real Gaia performance

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#48]
You should cite actual performance of Gaia in addition to the pre-launch projected performance.

**Comment by ivezic** [comment]
Wil, the list of potential assignees doesn't give me Leanne, but please feel free to recruit her to address this comment.

**Comment by womullan** [comment]
I see Leanne is in now on - I have asked Jos and Uwe for an update on http://adsabs.harvard.edu/abs/2012Ap%26SS.341...31D

**Comment by leannep** [comment]
Relevant and current Gaia papers are: 

Gaia Data Release 2: Summary of the contents and survey properties
https://www.aanda.org/component/article?access=doi&doi=10.1051/0004-6361/201833051
Table 3 gives the basic performance statistics for Gaia DR2. 

Gaia Data Release 2: The astrometric solution, Table B.1
https://doi.org/10.1051/0004-6361/201832727

Overview and stellar statistics of the expected Gaia Catalogue using the Gaia Object Generator, Section 3.3 
https://ui.adsabs.harvard.edu/#abs/2014A&A...566A.119L 
For DR3 projections using  ~34 months of mission time.

**Comment by womullan** [comment]
added to the bib file in order above
@ARTICLE{2018A&A...616A...1G,
@ARTICLE{2018A&A...616A...2L,
@ARTICLE{2014A&A...566A.119L,

on branch u/womullan/issue48   more to come

**Comment by timj** [comment]
Gaia information was updated in 5b88776 and 8102ae8.
