### ISSUE TITLE
ApJ #1: Telescope position too accurate

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#49]
The telescope latitude and longitude are specified to 0.01" which is 31 cm. Are these values really that good? And if so, what part of the telescope do they correspond too? That should be specified. [p 16]

**Comment by ivezic** [comment]
I find this comment rather amusing (and would like to know the answer myself). Chuck, can you please think of an appropriate response?

**Comment by cclaver** [comment]
The coordinates quoted come straight from Mamajek 2012 Table 3.  I am guessing, given the precision, these coordinates were what a GPS device reported.  GPS is certainly good to 31cm.  Further, I would guess that these coordinates represents the position of the base center of the telescope pier.  How much care was taken when these readings were made to place the GPS at the center of the pier is unknown.  The 2012 date means these measurements were made prior to excavation - also unknown how close the actual pier is to this location.  T&S may have updated coordinates based on where the concrete got poured.  I suggest that the coordinates be rounded to the arcsec.

**Comment by ivezic** [comment]
We have clarified that the listed coordinates correspond to the center of the telescope pier.
