### ISSUE TITLE
ApJ #1: Fix equation in footnote 14

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#50]
Footnote 14: there should be an S^2 term as well since there are flux errors proportional to the flux. The coefficient will probably be small but the term will be present.

**Comment by ivezic** [comment]
I will address this comment.

**Comment by ivezic** [comment]
If there is an S^2 term for some reason (and one would not expect it from the first principles, 
unless more complicated error models with various systematic effects are invoked), it must be 
very small; for example, Sesar et al. (2007) showed that our Eq.5 is supported by the empirical SDSS 
photometric behavior. More details about our SNR computation are available in Section 4 from http://faculty.washington.edu/ivezic/Teaching/Astr511/LSST_SNRdoc.pdf
