### ISSUE TITLE
ApJ #1: Equation inconsistency

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#51]
Eqn 6 & 7: These are not consistent in their treatment of the exposure time. Eqn(6) is pure sqrt(t) while Eqn(7) is poorly written and not explained well. \Delta C^\infty_m is not the loss due to readout noise when the integration time goes to infinity, because that is zero. Rewrite to explain better.

**Comment by ivezic** [comment]
I will address this comment.

**Comment by ivezic** [comment]
We have clarified the details behind Eqs. 6 and 7 in the revised version.
