### ISSUE TITLE
ApJ #1: Science cases are stale and need updating

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#52]
Given the 10 year history of this paper, some of the science discussions are stale and should be updated.

**Comment by ivezic** [comment]
We need to reiterate in the response to the referee that the paper was updated a few months ago, including the chairs of science collaborations updating all science discussions (which can be gauged from the refreshed references). There is no action on this point.

**Comment by timj** [comment]
The response to the referee was committed in 3ad79094c8d39b119b6a8e34ed709f842acbfcc2
