### ISSUE TITLE
Abstract is too long

### ISSUE THREAD

**Issue by timj** [lsst-pst/overview_paper#56]
AAS have a word count limit for abstracts of 250 words. The abstract is currently 473 words so needs to be trimmed substantially.

cc/ @chrislintott in case there is any wiggle room.

**Comment by chrislintott** [comment]
I will try to get us wriggle, and rewrite if not.

Chris


On 8 Jan 2019, at 11:52, Tim Jenness <notifications@github.com<mailto:notifications@github.com>> wrote:


AAS have a word count limit for abstracts of 250 words. The abstract is currently 473 words so needs to be trimmed substantially.

cc/ @chrislintott<https://github.com/chrislintott> in case there is any wiggle room.

**Comment by timj** [comment]
AAS have prodded me again for a response.

**Comment by chrislintott** [comment]
Thanks - i haven’t got an answer from the editor about a change, so I suggest we go with this short version.

Chris


On 14 Jan 2019, at 14:26, Zeljko Ivezic <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is a shortened version:
\begin{abstract}
We describe here the most ambitious survey currently planned in the optical,
the Large Synoptic Survey Telescope (LSST). The LSST design is driven by four
main science themes: probing dark energy and dark matter, taking an inventory
of the Solar System, exploring the transient optical sky, and mapping the Milky Way.
LSST will be a large, wide-field ground-based system designed to obtain repeated
images covering the sky visible from Cerro Pach'{o}n in northern Chile. The telescope
will have an 8.4 m (6.5 m effective) primary mirror, a 9.6 deg$^2$ field of view, a
3.2 Gigapixel camera, and six filters ($ugrizy$) covering the wavelength range
320--1050 nm. The project is in the construction phase and will begin regular survey
operations by 2022. About 90% of the observing time will be devoted to a deep-wide-fast
survey mode which will uniformly observe a 18,000 deg$^2$ region about 800 times
(summed over all six bands) during the anticipated 10 years of operations, and will
yield a coadded map to $r\sim27.5$. These data will result in databases including about
32 trillion observations of 20 billion galaxies and a similar number of stars, and will
serve the majority of the primary science programs. The remaining 10% of the observing
time will be allocated to special projects such as a Very Deep and Very Fast time-domain
surveys, whose details are currently under discussion. We illustrate how the LSST science
drivers led to these choices of system parameters, and describe the expected data products
and their characteristics.
\end{abstract}

**Comment by timj** [comment]
Fixed in commit 6e6b692 and resubmitted to AAS.
